'use strict';
const $=s=>document.querySelector(s), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let auth={}, data=null, tab='devices', refreshing=false;
let setupToken=new URLSearchParams(location.hash.slice(1)).get('setup')||'';
history.replaceState(null,'',location.pathname);
const titles={devices:['Tổng quan nhân viên','Nhân viên, máy và tài nguyên — theo dõi trong cùng một màn hình.','Nhân viên & máy'],uploads:['Lịch sử upload','100 file được cấp phiên gần nhất và kết quả xác minh trên Drive.','File gần đây'],articles:['Thư mục bài','Kiểm tra ảnh và video được phân vào đúng bài trên Google Drive.','100 thư mục bài gần đây'],channels:['Quản lý kênh','Thiết lập tên và mã kênh để phân loại tài nguyên.','Danh sách kênh'],system:['Máy chủ','Kết nối Google, kiểm tra hoạt động và chuẩn bị thư mục.','Thông tin kết nối']};
const labels={starting:'Đang mở',scanning:'Đang quét',hashing:'Kiểm tra file',uploading:'Đang upload',verifying:'Đang xác minh',waiting:'Đang theo dõi',error:'Có lỗi',stopped:'Đã dừng',verified:'Đã xác minh',issued:'Đã cấp phiên'};
async function api(path,payload,extra={}){const r=await fetch(path,{method:payload===undefined?'GET':'POST',credentials:'same-origin',headers:payload===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':auth.csrf||'',...extra},body:payload===undefined?undefined:JSON.stringify(payload)});let v;try{v=await r.json();}catch{throw Error('Máy chủ chưa phản hồi đúng. Kiểm tra kết nối.');}if(!r.ok){if(r.status===401&&path!='/api/login'){auth.authenticated=false;showAuth();}throw Error(v.error||'Thao tác chưa hoàn tất.');}return v;}
function notice(text,error=false){const n=$('#notice');n.textContent=text;n.className='notice'+(error?' error':'');n.hidden=!text;}
function showAuth(){const logged=!!auth.authenticated;$('#auth-view').hidden=logged;$('#app-view').hidden=!logged;if(logged){$('#username').textContent=auth.username;return;}const setup=!auth.configured&&auth.local&&setupToken;$('#auth-title').textContent=setup?'Tạo tài khoản quản trị':'Đăng nhập DriveDrop';$('#auth-submit').textContent=setup?'Tạo tài khoản':'Đăng nhập';$('#auth-form').hidden=!auth.configured&&!setup;$('#auth-help').textContent=setup?'Thiết lập lần đầu trên máy chủ. Dùng tài khoản này khi truy cập website.':auth.configured?'Quản lý máy nhân viên và tài nguyên Google Drive.':'Mở DriveDrop trên máy chủ và bấm Quản trị web để thiết lập tài khoản trước.';$('#auth-form').elements.password.autocomplete=setup?'new-password':'current-password';}
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();const b=$('#auth-submit');b.disabled=true;$('#auth-error').textContent='';try{const payload=Object.fromEntries(new FormData(e.target));if(!auth.configured){await api('/api/setup',payload,{'X-Setup-Token':setupToken});setupToken='';}await api('/api/login',payload);e.target.reset();auth=await api('/api/auth');showAuth();await refresh();}catch(err){$('#auth-error').textContent=err.message;}finally{b.disabled=false;}});
$('#logout').onclick=async()=>{try{await api('/api/logout',{});auth=await api('/api/auth');data=null;$('#content').replaceChildren();showAuth();}catch(e){notice(e.message,true);}};
function badge(text,kind=''){return el('span',text,'badge '+kind);}
function button(text,action,cls='quiet'){const b=el('button',text,cls);b.type='button';b.onclick=action;return b;}
function size(n){if(!n)return '—';const i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return (n/1024**i).toLocaleString('vi-VN',{maximumFractionDigits:1})+' '+['B','KB','MB','GB'][i];}
function when(n){return n?new Date(n*1000).toLocaleString('vi-VN'):'Chưa gửi trạng thái';}
function cell(...nodes){const td=el('td');nodes.forEach(n=>td.append(typeof n==='string'?document.createTextNode(n):n));return td;}
function table(headers,rows){const wrap=el('div',undefined,'table-wrap'),t=el('table'),thead=el('thead'),hr=el('tr');headers.forEach(x=>hr.append(el('th',x)));thead.append(hr);t.append(thead);const body=el('tbody');rows.forEach(cells=>{const r=el('tr');cells.forEach(c=>r.append(c instanceof HTMLElement?c:cell(String(c??'—'))));body.append(r);});t.append(body);wrap.append(t);return wrap;}
function empty(title,text,action){const n=el('div',undefined,'empty');n.append(el('div','▤','empty-icon'),el('h3',title),el('p',text));if(action)n.append(action);return n;}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function act(path,payload,success){try{await api(path,payload);notice(success);await refresh();}catch(e){notice(e.message,true);}}
function channelDialog(row){const f=$('#channel-form');f.reset();for(const key of ['id','name','code'])f.elements[key].value=row?.[key]||'';$('#channel-title').textContent=row?'Sửa kênh':'Thêm kênh';f.querySelector('.error').textContent='';$('#channel-dialog').showModal();}
function render(){if(!data)return;const content=$('#content'),focused=document.activeElement,focusId=focused?.dataset.folderSearch,caret=focused?.selectionStart;content.replaceChildren();const q=$('#search').value.trim().toLocaleLowerCase(),match=r=>JSON.stringify(r).toLocaleLowerCase().includes(q);$('#page-title').textContent=titles[tab][0];$('#page-desc').textContent=titles[tab][1];$('#panel-title').textContent=titles[tab][2];$('#search').hidden=tab==='system';let rows=[];
 if(tab==='devices')rows=renderDevices(content,q);
 if(tab==='uploads'){rows=data.uploads.filter(match);content.append(rows.length?table(['Tên file','Đích trên Drive','Dung lượng','Kết quả','Thời gian'],rows.map(r=>[cell(el('strong',r.name),el('small',data.devices.find(d=>d.id===r.device)?.name||r.device)),cell(r.destination||'Chưa có'),size(r.size),cell(badge(labels[r.state]||r.state,r.state==='verified'?'good':'')),when(r.created)])):empty('Chưa có file phù hợp','Các file xuất hiện ở đây khi máy nhân viên yêu cầu phiên upload.'));}
 if(tab==='articles'){rows=data.articles.filter(match);content.append(rows.length?table(['Máy','Thư mục bài trên Drive','Ảnh đã xác minh','Video đã xác minh','Đã cấp phiên / xác minh','Dung lượng','Gần nhất'],rows.map(r=>[r.name,r.folder,number(r.images),number(r.videos),r.issued+' / '+r.verified,size(r.bytes),when(r.recent)])):empty('Chưa có thư mục bài phù hợp','Bài sẽ hiển thị sau khi máy nhân viên bắt đầu gửi file.'));}
 if(tab==='channels'){rows=data.channels.filter(match);const bar=el('div',undefined,'system-actions');bar.append(button('+ Thêm kênh',()=>channelDialog(),'primary'),button('Tạo thư mục Drive',()=>startJob('sync')));const wrapper=el('div',undefined,'system');wrapper.append(bar);content.append(wrapper);content.append(rows.length?table(['Tên kênh','Mã kênh','Trạng thái','Thao tác'],rows.map(r=>{const actions=el('div',undefined,'row-actions');actions.append(button('Sửa',()=>channelDialog(r)),button(r.enabled?'Tắt kênh':'Bật kênh',()=>act('/api/channels/enable',{id:r.id,enabled:!r.enabled},'Đã cập nhật kênh.')));return [r.name,r.code,cell(badge(r.enabled?'Đang bật':'Đã tắt',r.enabled?'good':'')),cell(actions)];})):empty('Chưa có kênh phù hợp','Thêm tên và mã kênh để phân loại ảnh, video.'));}
 if(tab==='system'){const box=el('div',undefined,'system'),dl=el('dl');[['Tên miền dự kiến',data.public_url],['Google trên máy chủ',data.google_connected?'Đã lưu thông tin kết nối · cần thử upload để xác nhận':'Chưa kết nối'],['Phiên bản','DriveDrop '+data.version],['Luồng ảnh / video','Máy nhân viên → Google Drive'],['Thiết lập Google','Thực hiện trong ứng dụng DriveDrop trên máy 192.168.1.105']].forEach(([a,b])=>dl.append(el('dt',a),el('dd',b)));box.append(dl);const buttons=el('div',undefined,'system-actions');buttons.append(button('Thử upload thật',()=>startJob('selftest'),'primary'),button('Kiểm tra HTTPS và kho khóa',()=>startJob('diagnostics')),button('Tạo thư mục Drive',()=>startJob('sync')));box.append(buttons,el('h2','Tác vụ gần nhất'));const job=data.job;box.append(el('p',({idle:'Chưa chạy tác vụ',running:'Đang chạy',done:'Hoàn tất',error:'Có lỗi'})[job.state]));box.append(el('pre',job.log.join('\n')||'Kết quả kiểm tra sẽ xuất hiện ở đây.','job-log'));content.append(box);}
 reportStats();if(focusId){const next=[...document.querySelectorAll('[data-folder-search]')].find(n=>n.dataset.folderSearch===focusId);if(next){next.focus();next.setSelectionRange(caret,caret);}}$('#row-count').textContent=tab==='system'?'Máy chủ Windows':rows.length+' mục';}
async function refresh(){if(refreshing||!auth.authenticated)return;refreshing=true;try{data=await api('/api/dashboard');$('#version').textContent=data.version;$('#google-warning').hidden=data.google_connected;$('#updated').textContent='Cập nhật '+new Date().toLocaleTimeString('vi-VN');render();}catch(e){if(auth.authenticated)notice(e.message,true);}finally{refreshing=false;}}
function setTab(name){tab=name;$('#search').value='';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render();}
function startJob(name){if(name==='selftest'&&!confirm('Tạo các ảnh kiểm thử nhỏ trên Google Drive để kiểm tra upload thật?'))return;act('/api/job',{name},'Đã bắt đầu tác vụ. Xem tiến độ tại Máy chủ.');setTab('system');}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#search').oninput=()=>{devicePage=0;render();};$('#export-report').onclick=exportReport;$('#refresh').onclick=refresh;$('#enroll-open').onclick=()=>{$('#enroll-form .error').textContent='';$('#enroll-dialog').showModal();};
$('#enroll-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;try{const v=await api('/api/enroll',Object.fromEntries(new FormData(e.target)));download(v,'DriveDrop-kich-hoat.json');$('#enroll-dialog').close();notice('Đã tải file kích hoạt. Gửi riêng cho đúng nhân viên và nhập trong vòng 15 phút.');e.target.reset();}catch(err){e.target.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};
$('#channel-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;try{const v=Object.fromEntries(new FormData(e.target));if(!v.id)delete v.id;await api('/api/channels/save',v);$('#channel-dialog').close();notice('Đã lưu kênh. Có thể tạo thư mục Drive khi Google đã kết nối.');await refresh();}catch(err){e.target.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};
(async()=>{try{auth=await api('/api/auth');showAuth();await refresh();}catch(e){$('#auth-error').textContent=e.message;}})();setInterval(refresh,5000);

$('#profile-form').elements.employee_code.onchange=e=>{const existing=data.devices.find(d=>d.employee_code===e.target.value.trim().toUpperCase());if(existing)$('#profile-form').elements.employee_name.value=existing.employee_name;};
$('#profile-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('.primary');b.disabled=true;try{await api('/api/devices/profile',Object.fromEntries(new FormData(e.target)));$('#profile-dialog').close();notice('Đã lưu nhân viên và máy.');await refresh();}catch(err){e.target.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};
